services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}_dev
    env_file:
      - .env.local
    ports:
      - "5001:5000"
    volumes:
      - ./apps/backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    networks:
      - tiptop-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - tiptop-network

  postgres:
    image: postgres:14
    ports:
      - "5433:5432"
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tiptop-network

volumes:
  postgres_data:

networks:
  tiptop-network:
    driver: bridge
