services:
  # Reverse Proxy
  traefik:
    image: traefik:v2.10
    command:
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=admin@tiptop.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./infrastructure/reverse-proxy/letsencrypt:/letsencrypt
    networks:
      - tiptop-network

  # Backend
  backend:
    build: ./apps/backend
    ports:
      - "5001:5000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - "traefik.http.routers.backend.rule=Host(`api.tiptop.com`)"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
    networks:
      - tiptop-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  # Frontend
  frontend:
    build: ./apps/frontend
    ports:
      - "3003:3000"
    labels:
      - "traefik.http.routers.frontend.rule=Host(`tiptop.com`)"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
    networks:
      - tiptop-network

  # Monitoring
  grafana:
    image: grafana/grafana-oss:9.5.6
    ports:
      - "3002:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - tiptop-network

  prometheus:
    image: prom/prometheus:v2.47.0
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - tiptop-network

  alertmanager:
    image: prom/alertmanager:v0.25.0
    volumes:
      - ./infrastructure/monitoring/alertmanager/config.yml:/etc/alertmanager/config.yml
    networks:
      - tiptop-network

  loki:
    image: grafana/loki:2.8.2
    volumes:
      - ./infrastructure/monitoring/loki/loki-config.yml:/etc/loki/local-config.yaml
    networks:
      - tiptop-network


  # Base de données principale
  postgres:
    image: postgres:14
    ports:
      - "5434:5432"
    env_file: .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tiptop-network

  # Base de données dédiée pour SonarQube
  postgres-sonar:
    image: postgres:14
    container_name: postgres-sonar
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: ${SONAR_JDBC_USERNAME}
      POSTGRES_PASSWORD: ${SONAR_JDBC_PASSWORD}
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      - tiptop-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${SONAR_JDBC_USERNAME}"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  # CI/CD
  jenkins:
    build: ./infrastructure/ci-cd/jenkins
    image: tiptop/jenkins-custom:latest
    user: root
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    networks:
      - tiptop-network

  # SonarQube
  sonarqube:
    image: sonarqube:latest
    depends_on:
      postgres-sonar:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres-sonar:5432/sonar
      SONAR_JDBC_USERNAME: ${SONAR_JDBC_USERNAME}
      SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD}
    ports:
      - "9000:9000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarqube.rule=Host(`sonarqube.tiptop.com`)"
      - "traefik.http.routers.sonarqube.entrypoints=websecure"
      - "traefik.http.routers.sonarqube.tls.certresolver=letsencrypt"
      - "traefik.http.services.sonarqube.loadbalancer.server.port=9000"
    networks:
      - tiptop-network

volumes:
  postgres_data:
  sonar_db_data:
  sonarqube_data:
  sonarqube_extensions:
  pgadmin_data:
  jenkins_data:
  prometheus_data:
  grafana_data:

networks:
  tiptop-network:
    driver: bridge
