services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_dev}
      MYSQL_DATABASE: ${MYSQL_DATABASE_dev}
      MYSQL_USER: ${MYSQL_USER_dev}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_dev}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "${MYSQL_USER_dev}", "-p${MYSQL_PASSWORD_dev}"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - tiptop-network

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER_dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_dev}
      POSTGRES_DB: ${POSTGRES_DB_dev}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tiptop-network

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://${MYSQL_USER_dev}:${MYSQL_PASSWORD_dev}@mysql:3306/${MYSQL_DATABASE_dev}
    env_file:
      - .env
      - apps/backend/.env
    ports:
      - "5001:5000"
    volumes:
      - backend_node_modules:/usr/src/app/node_modules
      - ./apps/backend/.env:/var/www/html/.env
    depends_on:
      - mysql
    command: /usr/local/bin/wait-for-mysql.sh && composer install --prefer-dist --no-progress --no-interaction && php bin/console cache:clear --no-warmup
    networks:
      - tiptop-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.dev.tiptop.com`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=5001"

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - "3002:4200"
    volumes:
      - ./apps/frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - tiptop-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.tiptop.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=3002"

networks:
  tiptop-network:
    driver: bridge

volumes:
  mysql_data:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:
