services:
  # Reverse Proxy avec Let's Encrypt
  traefik:
    image: traefik:v2.10
    command:
      - --providers.docker
      - --entrypoints.web.address=:8090
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=admin@tiptop.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    ports:
      - "8090:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./infrastructure/reverse-proxy/letsencrypt:/letsencrypt
    networks:
      - tiptop-network

  # Backend
  backend:
    build: ./apps/backend
    ports:
    - "5000:5000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    labels:
      - "traefik.http.routers.backend.rule=Host(`api.tiptop.com`)"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tiptop-network

  # Frontend
  frontend:
    build: ./apps/frontend
    ports:
    - "3003:3000" 
    labels:
      - "traefik.http.routers.frontend.rule=Host(`tiptop.com`)"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
    networks:
      - tiptop-network

  # Monitoring avec Loki et Alertmanager
  grafana:
    image: grafana/grafana-oss:9.5.6
    ports:
      - "3002:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - tiptop-network

  prometheus:
    image: prom/prometheus:v2.47.0
    ports:
    - "9090:9090"
    volumes:
      - ./infrastructure/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - tiptop-network

  alertmanager:
    image: prom/alertmanager:v0.25.0
    volumes:
      - ./infrastructure/monitoring/alertmanager/config.yml:/etc/alertmanager/config.yml
    networks:
      - tiptop-network

  loki:
    image: grafana/loki:2.8.2
    volumes:
      - ./infrastructure/monitoring/loki/loki-config.yml:/etc/loki/local-config.yaml
    networks:
      - tiptop-network

  # Bases de données

  postgres:
    image: postgres:15.4-alpine
    ports:
      - "5434:5432"
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]  # Remplacez ${POSTGRES_USER} par "postgres"
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tiptop-network

  # CI/CD
  jenkins:
    build: ./infrastructure/ci-cd/jenkins
    image: tiptop/jenkins-custom:latest
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    networks:
      - tiptop-network

  sonarqube:
    image: sonarqube:10.2.1-community
    depends_on:
      - postgres
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONAR_JDBC_USERNAME=${SONAR_JDBC_USERNAME}
      - SONAR_JDBC_PASSWORD=${SONAR_JDBC_PASSWORD}
    ports:
      - "9000:9000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarqube.rule=Host(`sonarqube.tiptop.com`)"  # je vais remplacer ceci plus tard par mon domaine ou sous domaine.
      - "traefik.http.routers.sonarqube.entrypoints=websecure"
      - "traefik.http.routers.sonarqube.tls.certresolver=letsencrypt"
    networks:
      - tiptop-network

volumes:
  postgres_data:
  pgadmin_data:
  jenkins_data:
  prometheus_data:
  grafana_data:

networks:
  tiptop-network:
    driver: bridge
