services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    environment:
      NODE_ENV: development
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data/mydatabase_dev.sqlite"  # Connexion à SQLite
    entrypoint: ["php-fpm"]
    command: ["php-fpm"]
    env_file:
      - apps/backend/.env
    ports:
      - "5001:5000"
    volumes:
      - backend_node_modules:/usr/src/app/node_modules
      - ./apps/backend:/var/www/html
      - ./apps/backend/.env:/var/www/html/.env
      - backend_db:/var/www/html/var/data  # Volume pour SQLite
    networks:
      - tiptop-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - "3002:4200"
    volumes:
      - ./apps/frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    networks:
      - tiptop-network

networks:
  tiptop-network:
    driver: bridge

volumes:
  backend_node_modules:
  frontend_node_modules:
  backend_db:  # Volume pour la base de données SQLite
