services:
  backend:
    image: thierrytemgoua98/mon-backend:latest
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://backend:backendpass@postgres_backend:5434/backenddb
    ports:
      - "5002:5000"
    networks:
      - tiptop-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.preprod.tiptop.com`)"

  frontend:
    image: thierrytemgoua98/mon-frontend:latest
    environment:
      NODE_ENV: production
    ports:
      - "3002:8081"
    networks:
      - tiptop-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.preprod.tiptop.com`)"

  postgres_sonarqube:
    image: postgres:14
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: mydatabase_preprod
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sonar"]
      interval: 30s
      retries: 5
      start_period: 15s
      timeout: 5s
    ports:
      - "5433:5432"
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      - tiptop-network

  postgres_backend:
    image: postgres:14
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backendpass
      POSTGRES_DB: backenddb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "backend"]
      interval: 30s
      retries: 5
      start_period: 15s
      timeout: 5s
    ports:
      - "5434:5432"
    volumes:
      - backend_db_data:/var/lib/postgresql/data
    networks:
      - tiptop-network

networks:
  tiptop-network:
    driver: bridge

volumes:
  backend_db_data:
  sonar_db_data:
