# Étape 1 : Construire l'application Angular
FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
COPY . .
RUN npm run build --configuration=production

# Étape 2 : Créer l'image de production avec Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
# Exposer sur 8081 pour éviter les conflits avec Traefik
EXPOSE 8081
CMD ["nginx", "-g", "daemon off;"]
