# Étape 1 : Construire l'application Angular
FROM node:18 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY . .

# Construire l’application Angular en mode production
RUN npm run build --configuration=production

# Étape 2 : Configurer Nginx pour servir l'application
FROM nginx:alpine

# Copier la configuration optimisée de Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Copier les fichiers de build Angular dans le répertoire de Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Lancer Nginx
CMD ["nginx", "-g", "daemon off;"]
