# Étape 1 : Utiliser une image Node optimisée
FROM node:18 AS dev

# Définir le répertoire de travail
WORKDIR /app

# Copier uniquement les fichiers package.json et package-lock.json pour optimiser le cache
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code source de l'application Angular
COPY . .

# Activer les volumes pour éviter la perte des modules node_modules
VOLUME [ "/app/node_modules" ]

# Exposer le port par défaut d'Angular (4200)
EXPOSE 4200

# Lancer l’application en mode développement
CMD ["npm", "start"]
