# Étape 1 : Utiliser une image Node optimisée
FROM node:18 AS dev

# Définir le répertoire de travail
WORKDIR /app

# Copier uniquement les fichiers package.json et package-lock.json pour optimiser le cache
COPY package.json package-lock.json ./

# Installer les dépendances avec npm ci pour une installation plus rapide et stable
RUN npm ci

# Copier tout le code source de l'application Angular
COPY . .

# Exposer le port par défaut d'Angular (4200)
EXPOSE 4200

# Lancer l’application en mode développement
CMD ["npm", "start"]
