# Utilisation de Node.js 20 pour le développement
FROM node:20-alpine

# Définir le répertoire de travail
WORKDIR /usr/src/app

# Copier package.json et package-lock.json
COPY package*.json ./

# Installer toutes les dépendances (y compris celles de développement)
RUN npm install

# Copier le code source dans le conteneur
COPY . .

# Exposer le port que NestJS utilise pour la dev
EXPOSE 5000

# Démarrer l'application en mode développement
CMD ["npm", "run", "start:dev"]
