FROM php:8.2-fpm

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y \
    git unzip libpq-dev libzip-dev libicu-dev \
    libonig-dev libxml2-dev curl libcurl4-openssl-dev \
    default-mysql-client \
    && docker-php-ext-install pdo_mysql zip intl opcache mbstring xml curl

# Installer Composer globalement
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN apt-get install -y wait-for-it

# Copier le script wait-for-mysql.sh dans le conteneur
COPY apps/backend/wait-for-mysql.sh /usr/local/bin/wait-for-mysql.sh

# Donner les permissions d'exécution au script
RUN chmod +x /usr/local/bin/wait-for-mysql.sh

# Copier tout le code source
COPY apps/backend/ /var/www/html/

EXPOSE 5000

# Exécuter Composer et d'autres commandes après que le script wait-for-mysql.sh ait vérifié MySQL
CMD /usr/local/bin/wait-for-mysql.sh mysql:3306 -- composer install --prefer-dist --no-progress --no-interaction && php bin/console cache:clear --no-warmup && php-fpm
