FROM php:8.2-fpm

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y \
    git unzip libpq-dev libzip-dev libicu-dev \
    libonig-dev libxml2-dev curl libcurl4-openssl-dev \
    && docker-php-ext-install pdo_pgsql zip intl opcache mbstring xml dom curl

# Installer Composer globalement
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN apt-get install -y wait-for-it

# Copier le script wait-for-postgres.sh dans le conteneur
COPY apps/backend/wait-for-postgres.sh /usr/local/bin/wait-for-postgres.sh

# Donner les permissions d'exécution au script
RUN chmod +x /usr/local/bin/wait-for-postgres.sh

# Copier tout le code source
COPY apps/backend/ /var/www/html/

COPY apps/backend/docker-entrypoint.sh /usr/src/app/docker-entrypoint.sh
RUN chmod +x /usr/src/app/docker-entrypoint.sh

EXPOSE 5000

# Exécuter Composer et d'autres commandes après que le script wait-for-postgres.sh ait vérifié PostgreSQL
CMD /usr/local/bin/wait-for-postgres.sh postgres 5433 bdd_user bdd_pass -- sh -c "composer install --prefer-dist --no-progress --no-interaction && php bin/console cache:clear --no-warmup && php-fpm"
