services:
  backend:
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}_dev
    ports:
      - "3001:3000"

  frontend:
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"