services:
  backend:
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}_dev
    ports:
      - "3001:3000"

  frontend:
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"

  mysql:
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}_dev
